

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
		fontFamily: {
			sans: ["Open Sans"]
		},
		gridTemplateColumns: {
			"1/5" : "1fr 5fr"
		},
		colors: {
			customColors: {
			  "1": "#9F2957",
			  "2": "#d90056",
			  "3": "#e25d33",
			  "4": "#dfc45a",
			  "5": "#b8c42f",
			  "6": "#16af6e",
			  "7": "#424988",
			  "8": "#397e49",
			  "9": "#439bdf",
			  "10": "#4254af",
			  "11": "#6c7ac4",
			  "12": "#8332a4",
			},
		  },
	},
  },
  variants: {
    extend: {
      backgroundColor: ['hover', 'focus', 'active'],
      borderColor: ['focus', 'checked'],
    },
  },
  plugins: [require("@tailwindcss/forms")],
  safelist: [
    "text-customColors-1",
    "text-customColors-2",
    "text-customColors-3",
    "text-customColors-4",
    "text-customColors-5",
    "text-customColors-6",
    "text-customColors-7",
    "text-customColors-8",
    "text-customColors-9",
    "text-customColors-10",
    "text-customColors-11",
    "text-customColors-12",
    "bg-customColors-1",
    "bg-customColors-2",
    "bg-customColors-3",
    "bg-customColors-4",
    "bg-customColors-5",
    "bg-customColors-6",
    "bg-customColors-7",
    "bg-customColors-8",
    "bg-customColors-9",
    "bg-customColors-10",
    "bg-customColors-11",
    "bg-customColors-12",
    "checked:bg-customColors-1",
    "checked:bg-customColors-2",
    "checked:bg-customColors-3",
    "checked:bg-customColors-4",
    "checked:bg-customColors-5",
    "checked:bg-customColors-6",
    "checked:bg-customColors-7",
    "checked:bg-customColors-8",
    "checked:bg-customColors-9",
    "checked:bg-customColors-10",
    "checked:bg-customColors-11",
    "checked:bg-customColors-12",
    "border-customColors-1",
    "border-customColors-2",
    "border-customColors-3",
    "border-customColors-4",
    "border-customColors-5",
    "border-customColors-6",
    "border-customColors-7",
    "border-customColors-8",
    "border-customColors-9",
    "border-customColors-10",
    "border-customColors-11",
    "border-customColors-12",
  ],
};
